export { useScriptTriggerConsent, useScriptEventPage, useScriptTriggerElement, useScript, useScriptGoogleAnalytics, useScriptPlausibleAnalytics, useScriptCrisp, useScriptClarity, useScriptCloudflareWebAnalytics, useScriptFathomAnalytics, useScriptMatomoAnalytics, useScriptGoogleTagManager, useScriptGoogleAdsense, useScriptSegment, useScriptMetaPixel, useScriptXPixel, useScriptIntercom, useScriptHotjar, useScriptStripe, useScriptLemonSqueezy, useScriptVimeoPlayer, useScriptYouTubePlayer, useScriptGoogleMaps, useScriptNpm, useScriptUmamiAnalytics, useScriptSnapchatPixel, useScriptRybbitAnalytics, useScriptDatabuddyAnalytics, useScriptRedditPixel, useScriptPayPal } from '#app/composables/script-stubs';
export { isVue2, isVue3 } from 'vue-demi';
export { defineNuxtLink } from '#app/components/nuxt-link';
export { useNuxtApp, tryUseNuxtApp, defineNuxtPlugin, definePayloadPlugin, useRuntimeConfig, defineAppConfig } from '#app/nuxt';
export { useAppConfig, updateAppConfig } from '#app/config';
export { defineNuxtComponent } from '#app/composables/component';
export { useAsyncData, useLazyAsyncData, useNuxtData, refreshNuxtData, clearNuxtData } from '#app/composables/asyncData';
export { useHydration } from '#app/composables/hydrate';
export { callOnce } from '#app/composables/once';
export { useState, clearNuxtState } from '#app/composables/state';
export { clearError, createError, isNuxtError, showError, useError } from '#app/composables/error';
export { useFetch, useLazyFetch } from '#app/composables/fetch';
export { useCookie, refreshCookie } from '#app/composables/cookie';
export { onPrehydrate, prerenderRoutes, useRequestHeader, useRequestHeaders, useResponseHeader, useRequestEvent, useRequestFetch, setResponseStatus } from '#app/composables/ssr';
export { onNuxtReady } from '#app/composables/ready';
export { preloadComponents, prefetchComponents, preloadRouteComponents } from '#app/composables/preload';
export { abortNavigation, addRouteMiddleware, defineNuxtRouteMiddleware, setPageLayout, navigateTo, useRoute, useRouter } from '#app/composables/router';
export { isPrerendered, loadPayload, preloadPayload, definePayloadReducer, definePayloadReviver } from '#app/composables/payload';
export { useLoadingIndicator } from '#app/composables/loading-indicator';
export { getAppManifest, getRouteRules } from '#app/composables/manifest';
export { reloadNuxtApp } from '#app/composables/chunk';
export { useRequestURL } from '#app/composables/url';
export { usePreviewMode } from '#app/composables/preview';
export { useRouteAnnouncer } from '#app/composables/route-announcer';
export { useRuntimeHook } from '#app/composables/runtime-hook';
export { useHead, useHeadSafe, useServerHeadSafe, useServerHead, useSeoMeta, useServerSeoMeta, injectHead } from '#app/composables/head';
export { onBeforeRouteLeave, onBeforeRouteUpdate, useLink } from 'vue-router';
export { withCtx, withDirectives, withKeys, withMemo, withModifiers, withScopeId, onActivated, onBeforeMount, onBeforeUnmount, onBeforeUpdate, onDeactivated, onErrorCaptured, onMounted, onRenderTracked, onRenderTriggered, onServerPrefetch, onUnmounted, onUpdated, computed, customRef, isProxy, isReactive, isReadonly, isRef, markRaw, proxyRefs, reactive, readonly, ref, shallowReactive, shallowReadonly, shallowRef, toRaw, toRef, toRefs, triggerRef, unref, watch, watchEffect, watchPostEffect, watchSyncEffect, onWatcherCleanup, isShallow, effect, effectScope, getCurrentScope, onScopeDispose, defineComponent, defineAsyncComponent, resolveComponent, getCurrentInstance, h, inject, hasInjectionContext, nextTick, provide, toValue, useModel, useAttrs, useCssModule, useCssVars, useSlots, useTransitionState, useId, useTemplateRef, useShadowRoot, Component, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue';
export { requestIdleCallback, cancelIdleCallback } from '#app/compat/idle-callback';
export { setInterval } from '#app/compat/interval';
export { definePageMeta } from '../node_modules/nuxt/dist/pages/runtime/composables';
export { defineLazyHydrationComponent } from '#app/composables/lazy-hydration';
export { useApi } from '../composables/useApi';
export { useAudit } from '../composables/useAudit';
export { useAuth } from '../composables/useAuth';
export { useBilling } from '../composables/useBilling';
export { useBillingQueue } from '../composables/useBillingQueue';
export { useBillingWorkspace } from '../composables/useBillingWorkspace';
export { useBuilders } from '../composables/useBuilders';
export { useCallQueue } from '../composables/useCallQueue';
export { useCameraEvents } from '../composables/useCameraEvents';
export { useCrewMessages } from '../composables/useCrewMessages';
export { useCrewPaging } from '../composables/useCrewPaging';
export { useCrewRoster } from '../composables/useCrewRoster';
export { useDeviceIntegration } from '../composables/useDeviceIntegration';
export { useEndOfDayReconciliation } from '../composables/useEndOfDayReconciliation';
export { useFaceSheet } from '../composables/useFaceSheet';
export { useFinancialHealth } from '../composables/useFinancialHealth';
export { useFireOperations } from '../composables/useFireOperations';
export { useFounderCompensation } from '../composables/useFounderCompensation';
export { useGPSTracking } from '../composables/useGPSTracking';
export { useLightsSirens } from '../composables/useLightsSirens';
export { useLob } from '../composables/useLob';
export { useMedicalCoding } from '../composables/useMedicalCoding';
export { useNEMSISExport } from '../composables/useNEMSISExport';
export { useNemsis } from '../composables/useNemsis';
export { useOCR } from '../composables/useOCR';
export { useOfficeAlly } from '../composables/useOfficeAlly';
export { usePTT } from '../composables/usePTT';
export { usePatientEncounter } from '../composables/usePatientEncounter';
export { usePatientStatement } from '../composables/usePatientStatement';
export { usePermissions } from '../composables/usePermissions';
export { usePhoneSystem } from '../composables/usePhoneSystem';
export { usePlatformPricing } from '../composables/usePlatformPricing';
export { useQueues } from '../composables/useQueues';
export { useRealtimeSubscriptions } from '../composables/useRealtimeSubscriptions';
export { useSLAAndPriority } from '../composables/useSLAAndPriority';
export { useStripe } from '../composables/useStripe';
export { useSystemHealth } from '../composables/useSystemHealth';
export { useTalkGroups } from '../composables/useTalkGroups';
export { useTaxSafety } from '../composables/useTaxSafety';
export { useTelehealth } from '../composables/useTelehealth';
export { useTripLogs } from '../composables/useTripLogs';
export { useValidationRules } from '../composables/useValidationRules';
export { useVehicleTelemetry } from '../composables/useVehicleTelemetry';